Add Microsoft Azure changes for 0.2.0 Kotless version
JetBrains/kotless pull request #106
Opened 2021-05-31 21:17 UTC by ValchukDmitry

2021-08-17 09:22 UTC, TanVD requested changes

2021-08-17 09:22 UTC, TanVD commented on dsl/ktor/cloud/ktor-lang-azure/src/main/kotlin/io/kotless/dsl/ktor/KotlessAzure.kt
> +        logger.info("hi")
Hm?

2021-08-17 09:36 UTC, ValchukDmitry commented on dsl/ktor/cloud/ktor-lang-azure/src/main/kotlin/io/kotless/dsl/ktor/KotlessAzure.kt
> +        logger.info("hi")
ohh

2021-08-23 09:21 UTC, TanVD commented on dsl/ktor/cloud/ktor-lang-azure/src/main/kotlin/io/kotless/dsl/ktor/KotlessAzure.kt
> +        logger.info("hi")
))

2021-09-27 08:43 UTC, merged